## Data Mgmt. & Visualization 1

### 1. Data

In [20]:
import pandas as pd

In [21]:
!pip install xlrd

Requirement already satisfied: xlrd in .\anaconda3\Lib\site-packages (2.0.2)

In [22]:
house = pd.read_excel("http://byungwan.com/class/House_Prices.xls")

In [23]:
house.shape

(128, 8)

In [24]:
house.head(10)

   HomeID   Price  SqFt  Bedrooms  Bathrooms  Offers Brick Neighborhood
0       1  114300  1790         2          2       2    No         East
1       2  114200  2030         4          2       3    No         East
2       3  114800  1740         3          2       1    No         East
3       4   94700  1980         3          2       3    No         East
4       5  119800  2130         3          3       3    No         East
5       6  114600  1780         3          2       2    No        North
6       7  151600  1830         3          3       3   Yes         West
7       8  150700  2160         4          2       2    No         West
8       9  119200  2110         4          2       3    No         East
9      10  104000  1730         3          3       3    No         East

In [25]:
house.tail()

     HomeID   Price  SqFt  Bedrooms  Bathrooms  Offers Brick Neighborhood
123     124  119700  1900         3          3       3   Yes         East
124     125  147900  2160         4          3       3   Yes         East
125     126  113500  2070         2          2       2    No        North
126     127  149900  2020         3          3       1    No         West
127     128  124600  2250         3          3       4    No        North

## 2. Creating Dummies

### 2.1 Using Maps

In [26]:
house["Brick_Yes1"] = house["Brick"].map({"No": 0, "Yes": 1})

In [29]:
house.head(10)

,HomeID,Price,SqFt,Bedrooms,Bathrooms,Offers,Brick,Neighborhood,Brick_Yes1
0,1,114300,1790,2,2,2,No,East,0
1,2,114200,2030,4,2,3,No,East,0
2,3,114800,1740,3,2,1,No,East,0
3,4,94700,1980,3,2,3,No,East,0
4,5,119800,2130,3,3,3,No,East,0
5,6,114600,1780,3,2,2,No,North,0
6,7,151600,1830,3,3,3,Yes,West,1
7,8,150700,2160,4,2,2,No,West,0
8,9,119200,2110,4,2,3,No,East,0
9,10,104000,1730,3,3,3,No,East,0

## 2.2. Using get dummies

In [33]:
brick_dummy = pd.get_dummies(house["Brick"], dtype=int)

In [34]:
brick_dummy.head()

   No  Yes
0   1    0
1   1    0
2   1    0
3   1    0
4   1    0

In [37]:
house["Brick_Yes2"] = brick_dummy["Yes"]

In [38]:
house.head(10)

,HomeID,Price,SqFt,Bedrooms,Bathrooms,Offers,Brick,Neighborhood,Brick_Yes1,Brick_Yes2
0,1,114300,1790,2,2,2,No,East,0,0
1,2,114200,2030,4,2,3,No,East,0,0
2,3,114800,1740,3,2,1,No,East,0,0
3,4,94700,1980,3,2,3,No,East,0,0
4,5,119800,2130,3,3,3,No,East,0,0
5,6,114600,1780,3,2,2,No,North,0,0
6,7,151600,1830,3,3,3,Yes,West,1,1
7,8,150700,2160,4,2,2,No,West,0,0
8,9,119200,2110,4,2,3,No,East,0,0
9,10,104000,1730,3,3,3,No,East,0,0

In [39]:
house["Neighborhood"].value_counts()

Neighborhood
East     45
North    44
West     39
Name: count, dtype: int64

In [42]:
neighborhood_dummy = pd.get_dummies(house["Neighborhood"], dtype=int)

In [43]:
neighborhood_dummy.head()

   East  North  West
0     1      0     0
1     1      0     0
2     1      0     0
3     1      0     0
4     1      0     0

In [44]:
house["Neighborhood_North"] = neighborhood_dummy["North"]

In [45]:
house.head()

,HomeID,Price,SqFt,Bedrooms,Bathrooms,Offers,Brick,Neighborhood,Brick_Yes1,Brick_Yes2,Neighborhood_North
0,1,114300,1790,2,2,2,No,East,0,0,0
1,2,114200,2030,4,2,3,No,East,0,0,0
2,3,114800,1740,3,2,1,No,East,0,0,0
3,4,94700,1980,3,2,3,No,East,0,0,0
4,5,119800,2130,3,3,3,No,East,0,0,0

In [46]:
house["Neighborhood_West"] = neighborhood_dummy["West"]

In [47]:
house.head()

,HomeID,Price,SqFt,Bedrooms,Bathrooms,Offers,Brick,Neighborhood,Brick_Yes1,Brick_Yes2,Neighborhood_North,Neighborhood_West
0,1,114300,1790,2,2,2,No,East,0,0,0,0
1,2,114200,2030,4,2,3,No,East,0,0,0,0
2,3,114800,1740,3,2,1,No,East,0,0,0,0
3,4,94700,1980,3,2,3,No,East,0,0,0,0
4,5,119800,2130,3,3,3,No,East,0,0,0,0

In [48]:
house = pd.read_excel("http://byungwan.com/class/House_Prices.xls")

In [49]:
house.head()

   HomeID   Price  SqFt  Bedrooms  Bathrooms  Offers Brick Neighborhood
0       1  114300  1790         2          2       2    No         East
1       2  114200  2030         4          2       3    No         East
2       3  114800  1740         3          2       1    No         East
3       4   94700  1980         3          2       3    No         East
4       5  119800  2130         3          3       3    No         East

In [51]:
house2 = pd.get_dummies(house, columns=["Brick", "Neighborhood"], drop_first=True, dtype=int)

In [55]:
house2.describe()

,HomeID,Price,SqFt,Bedrooms,Bathrooms,Offers,Brick_Yes,Neighborhood_North,Neighborhood_West
count,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000
mean,64.500000,130427.343750,2000.937500,3.023438,2.445312,2.578125,0.328125,0.343750,0.304688
std,37.094474,26868.770371,211.572431,0.725951,0.514492,1.069324,0.471376,0.476825,0.462084
min,1.000000,69100.000000,1450.000000,2.000000,2.000000,1.000000,0.000000,0.000000,0.000000
25%,32.750000,111325.000000,1880.000000,3.000000,2.000000,2.000000,0.000000,0.000000,0.000000
50%,64.500000,125950.000000,2000.000000,3.000000,2.000000,3.000000,0.000000,0.000000,0.000000
75%,96.250000,148250.000000,2140.000000,3.000000,3.000000,3.000000,1.000000,1.000000,1.000000
max,128.000000,211200.000000,2590.000000,5.000000,4.000000,6.000000,1.000000,1.000000,1.000000

## 2.3. Converting Numerical to Categorical

In [54]:
pd.cut(house2["Price"], )

,HomeID,Price,SqFt,Bedrooms,Bathrooms,Offers,Brick_Yes,Neighborhood_North,Neighborhood_West
0,1,114300,1790,2,2,2,0,0,0
1,2,114200,2030,4,2,3,0,0,0
2,3,114800,1740,3,2,1,0,0,0
3,4,94700,1980,3,2,3,0,0,0
4,5,119800,2130,3,3,3,0,0,0